# Generated by Django 5.1.3 on 2024-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('flower', 'Flower'), ('tree', 'Tree'), ('vegetable', 'Vegetable'), ('herb', 'Herb')], max_length=50)),
                ('is_edible', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='plants/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
