# Generated by Django 5.1.3 on 2024-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('herb', 'Herb'), ('tree', 'Tree'), ('flower', 'Flower'), ('vegetable', 'Vegetable'), ('fruit', 'Fruit')], max_length=50),
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='plants/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
